modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="ran_dom_things"
version="1.0.0"
displayName="Ran-Dom Things"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="chris, MCreator"

[[dependencies.ran_dom_things]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




